### ISSUE TITLE
Incohérence entre l'énoncé et les cas de test du problème Goodies

### ISSUE THREAD

**Issue by arnaud-m** [INSAlgo/coding-battle2020#13]
Bonjour,

Il est indiqué dans l'énoncé du problème Goodie (F) : 

> Sortie
> Afficher "POSSIBLE" si vous avez une possibilité de gagner à coup sûr, "IMPOS-
SIBLE" sinon.

Mais les fichiers d'output contiennent une réponse OUI/NON.
https://github.com/INSAlgo/coding-battle2020/blob/9da00dd86c99031beee2e3ca7e969c9906129040/contest/f_goodies/output/output0.txt#L1
https://github.com/INSAlgo/coding-battle2020/blob/9da00dd86c99031beee2e3ca7e969c9906129040/contest/f_goodies/output/output1.txt#L1

Par ailleurs, la solution ne semble pas savoir sur quel pied danser, car les deux réponses sont mélangées : 
https://github.com/INSAlgo/coding-battle2020/blob/9da00dd86c99031beee2e3ca7e969c9906129040/contest/f_goodies/sol/f_goodies.py#L59-L60

https://github.com/INSAlgo/coding-battle2020/blob/9da00dd86c99031beee2e3ca7e969c9906129040/contest/f_goodies/sol/f_goodies.py#L83-L87

Encore merci pour l'organisation du concours.

**Comment by Lgt2x** [comment]
Bonjour, l'incohérence a été corrigé dans la solution via la MR #15 , et va bientôt l'être pour l'énoncé. Merci pour votre vigilance !

**Comment by Gnomino** [comment]
Bonjour,
L'incohérence a été corrigée aussi dans le sujet.
Merci encore d'avoir rapporté le problème !
