### ISSUE TITLE
Incohérence de l'énoncé (Bingo)

### ISSUE THREAD

**Issue by Viince06** [INSAlgo/coding-battle2020#14]
Bonjour,
N'y aurait-il pas un soucis dans l'input de l'exemple 1 de l'exercice BINGO ?
[![image](https://user-images.githubusercontent.com/43722845/97014538-c150e700-154a-11eb-99ce-7627033a7ffe.png)
](url)
Selon l'énoncé, il y a donc 5 salles et 6 couloirs.
Or sur les lignes d'en dessous, 5 couloirs seulement sont spécifiés.
**Est-ce une erreur ou est-ce que l'input n'est pas obligé de spécifier tous les couloirs ?**
Merci

**Comment by Viince06** [comment]
j'ai exploré les input/output et c'est juste l'énonce qui est faux.

Par contre, j'obtiens 93,33% et je vois que c'est l'input/output 8 qui bug.
Il y a une erreur dans votre output8.txt, il devrait sortir "2" or dans votre output8.txt il y a "1".

**Comment by Gnomino** [comment]
Bonjour, 
L'énoncé du problème mis en ligne était une vieille version et il s'agissait bien d'une erreur dans l'exemple.

C'est désormais corrigé, merci de l'avoir rapporté !
